doc/HELPERS.md
lua/null-ls/helpers/generator_factory.lua
lua/null-ls/helpers/make_builtin.lua

Some  formatters don't actually return the code and just modify $FILENAME directly, for example `biome`.
With this option we can now avoid using a tempfile.
I'll have a PR for biome if this gets accepted.
Right now I'm using:
```lua
nls.builtins.formatting.biome.with({
args = {
'check',
'--apply',
'--formatter-enabled=true',
'--organize-imports-enabled=true',
'--skip-errors',
'$FILENAME',
},
ignore_stdout = true,
ignore_stderr = true,
to_temp_file = false,
}),
```

feat(ignore_stdout): option to ignore stdout 

---

doc/BUILTINS.md
lua/null-ls/builtins/formatting/templ.lua

Like in the PR https://github.com/stevearc/conform.nvim/pull/73 of conform.nvim made by @zbindenren.
I would also like to add support for the templ formatter in `none-ls.nvim`.

feat: add support for templ formatting built-in

---

doc/BUILTINS.md
lua/null-ls/builtins/diagnostics/vale.lua

Update some outdated links for https://vale.sh/
There may have been some updates to `vale` since this diagnostic was written. It generally requires you to run `vale sync` once right after you create your initial `.vale.ini`, to download styles. Is that ok for `none-ls` (I'm not too familiar with how this plugin usually works yet), or should the diagnostic be reworked to auto-call `vale sync` as long as a `.vale.ini` exists?

docs: update vale.sh links

---

lua/null-ls/builtins/diagnostics/swiftlint.lua

Swiftlint returns a `2` exit code when it detects errors in your code, I've added a check to account for that. Currently when trying to use it for diagnostics, none-ls assumes it has failed.

Updates swiftlint builtins to check exit code

---

lua/null-ls/builtins/formatting/leptosfmt.lua

It seems whenever I tried using leptosfmt using the CLI options that were in the none-ls config, I'd get this error:
```
$ leptosfmt --stdin=true --quiet=true
error: unexpected value 'true' for '--stdin' found; no more were expected
Usage: leptosfmt --stdin [INPUT_PATTERNS]...
For more information, try '--help'.
```
But using `leptosfmt --stdin --quiet` will work fine

fix: leptosfmt generator-options

---

lua/null-ls/logger.lua
test/spec/logger_spec.lua

NullLsLog command is currently broken and does nothing.

fix: broken log file path for NullLsLog

---

doc/CONFIG.md
lua/null-ls/client.lua
lua/null-ls/config.lua
lua/null-ls/utils/init.lua
test/spec/client_spec.lua
test/spec/utils/utils_spec.lua

In this PR I implement a `root_dir_async` config field and a `root_pattern_async` utility that asynchronously find a desired root directory. This addresses #11 and prevents none-ls from blocking Neovim on potentially slow FS traversals.
I haven't made it the default config, because I don't feel confident doing so yet as this could be breaking for users.

synchronous root dir setting contributes to suboptimal load times

---

lua/null-ls/builtins/diagnostics/trivy.lua

This PR adds a new checker for Trivy, the successor of tfsec. The implementation is similar to the terraform_validate one because everything Terraform is directory based.

feat(builtins): add Trivy checker

---

doc/null-ls.txt
lua/null-ls/builtins/diagnostics/protolint.lua
lua/null-ls/builtins/formatting/protolint.lua

As the `protolint` commit changes(https://github.com/yoheimuta/protolint/issues/340, https://github.com/yoheimuta/protolint/commit/1f2cba7a25adba6afcd8ea5e4fabb69cd4b8ef4f), I have to remove the rule `FILE_NAMES_LOWER_SNAKE_CASE` to make the `protolint` fix works.
I also tried add `extra_args`, but the `protolint` require the parameters before the target files.
After add this rule, the `diagnositics` broken, so we need more checks to pass the `decoded.lints` when its value is `vim.NIL`.

Fix `protolint` formating/diagnositics issues

---

lua/null-ls/builtins/code_actions/shellcheck.lua

The code action to "Disable ShellCheck rule ... for this line" would fail to generate under some circumstances (e.g. the error is on the first line). Handle this case so user no longer gets opaque error message

fix(shellcheck): generate disable action errors

---

lua/null-ls/helpers/diagnostics.lua
test/spec/builtins/diagnostics_spec.lua

When we parse the report produced by a source, we usually read and forward the column index, but in Lua, the index of a substring depends on the number of bytes in the string, not the number of printable characters.
For example, the line:
```
• Any rule whose heading is ~~struck through~~ is deprecated.
```
Produces the report:
```
text:1:47:"is deprecated" may be passive voice
```
But if we use that `47` to create the diagnostic, Lua will count 47 bytes, which will give us:
```lua
"~~ is deprecated"
```
Instead of
```lua
"is deprecated"
```
That's why we end up with the odd range described in #19.
Luckily, the Neovim team has a function to find the index we need through the function `vim.str_byteindex`.

fix: diagnostic range in multi-byte lines

---

doc/BUILTINS.md
lua/null-ls/builtins/formatting/d2_fmt.lua

This PR adds a formatter builtin for the [d2](https://github.com/terrastruct/d2) diagramming language.
I have manually tested and confirmed it works as expected.

Adds formatter for D2

---

lua/null-ls/logger.lua
test/spec/logger_spec.lua

they added .log suffix again
https://github.com/nvim-lua/plenary.nvim/pull/546

fix: plenary log path

---

lua/null-ls/builtins/formatting/ruff_format.lua

https://github.com/nvimtools/none-ls.nvim/pull/41 removed `ruff_format` by mistake, this is restoring it back.
Check https://github.com/nvimtools/none-ls.nvim/pull/41#issuecomment-1843406374 and https://github.com/nvimtools/none-ls.nvim/pull/41#issuecomment-1843410187 for an explanation to why they are not the same thing.

revert: Revert wrongly removed ruff_format

---

lua/null-ls/builtins/formatting/dprint.lua

dprint supports formatting Python with Ruff: https://dprint.dev/plugins/ruff/

feat: support Python with Ruff in dprint

---

doc/BUILTINS.md
lua/null-ls/builtins/formatting/pint.lua

Check if pint is available in PATH before using project specific version

feat(pint): Improve pint cmd

---

lua/null-ls/builtins/diagnostics/ruff.lua
lua/null-ls/builtins/formatting/ruff.lua
lua/null-ls/builtins/formatting/ruff_format.lua

- Updated Ruff URL.
- `ruff_format` is only for formatting, not a linter.

chore: update ruff meta info

---

lua/null-ls/builtins/formatting/npm_groovy_lint.lua

Fix npm-groovy-lint, `--failon none` causes the script to always exit 0 (desired in this case of formatting), and increase the timeout for the cli that can take time

fix(formatting): npm_groovy_lint.lua: fix timeout and no error

---

lua/null-ls/code-actions.lua

Not all code action sources want their actions to be sorted alphabetically.
The source itself should determine the order of the actions by how they add them to the return table.
See: https://github.com/nvimtools/none-ls.nvim/discussions/62

fix(code actions): don't sort actions by title

---

doc/BUILTINS.md
lua/null-ls/builtins/formatting/vfmt.lua

Hello
This pull request adds [vfmt](https://github.com/vlang/v/blob/master/doc/docs.md#v-fmt) as a builtin formatter for [Vlang](https://vlang.io) code.

feat(builtins): add vfmt as a formatting builtin

---

lua/null-ls/builtins/formatting/rubocop.lua

Enable `--server` by default since is way [faster](https://docs.rubocop.org/rubocop/usage/server.html) and rubocop has this feature for quite a while, without it its pretty laggy.

feat(rubocop): Enable --server by default

---

lua/null-ls/builtins/diagnostics/ansiblelint.lua

I installed ansiblelint and tried to make it work with none-ls but it seems the latest version (v6.22.x) I installed changed the output to the outdated (v5.x)
This code change makes sure it can handle the v6 format and keeps backwards compatibility with the legacy v5 via some simple object detection.
This is the new format you get from ansiblelint v6
```json
[
{
"type": "issue",
"check_name": "syntax-check[specific]",
"categories": [
"core"
],
"url": "https://ansible-lint.readthedocs.io/rules/syntax-check/",
"severity": "blocker",
"level": "error",
"description": "'tasks' is not a valid attribute for a PlaybookInclude",
"fingerprint": "62bced6ef793c4d2c8e8922429b1baf4d75f19a67d2c8cbe4c40967e90157b47",
"location": {
"path": "playbook/update-install-pusher.yml",
"positions": {
"begin": { …
```

fix(ansiblelint): Support to the latest output format

---

lua/null-ls/builtins/formatting/gleam_format.lua

[Gleam](https://gleam.run/) just got its 1.0 release and, after trying it out myself, I noticed it didn't have a builtin formatter in none-ls. So here I am adding it.

feat(builtins): add Gleam format

---

doc/BUILTINS.md
doc/builtins.json
lua/null-ls/builtins/_meta/filetype_map.lua
lua/null-ls/builtins/_meta/formatting.lua
lua/null-ls/builtins/formatting/findent.lua

This PR adds the builtin support for findent, the Fortran code formatter. I have tested it locally using none-ls from my fork, and it passes the tests as well (`make test`).

feat(builtins): add Fortran findent code formatter

---

doc/BUILTINS.md
lua/null-ls/builtins/code_actions/refactoring.lua

In the refactoring builtin, changed the instruction to use ```vim.lsp.buf.range_code_action()``` to use ```vim.lsp.buf.code_action()``` as the former was deprecated in favor of the latter. See [here](https://neovim.io/doc/user/deprecated.html#vim.lsp.buf.range_code_action)
Also removed the instruction to use telescope code action (deprecated as well. See [here](https://github.com/nvim-telescope/telescope.nvim/pull/1866/files))

docs(refactoring): accomodate changes in neovim api

---

.github/workflows/luarocks.yml
.github/workflows/release-please.yml

Hey :wave: 
This PR is part of a push to get neovim plugins on [LuaRocks](https://luarocks.org/labels/neovim).
See also:
- [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim), a new luarocks-based plugin manager.
- [this blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html).
* Add a release-please workflow that creates release PRs with SemVer versioning based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
* Add a workflow that publishes tags to LuaRocks when a tag or release is pushed.
The workflows are based on [this guide](https://github.com/vhyrro/sample-luarocks-plugin) by @vhyrro.
* On each merge to `main`, the `release-please` workflow creates (or updates an existing) release PR.
* You decide when to merge release PRs. …

feat: luarocks support

---

doc/BUILTINS.md
lua/null-ls/builtins/diagnostics/bean_check.lua

We already have `bean-format` as a builtin. This pull request adds the complementary diagnostics counterpart, `bean-check`.

feat(builtins): add bean-check linter

---

lua/null-ls/builtins/formatting/prettier.lua
lua/null-ls/builtins/formatting/prettierd.lua

I was using the filetypes `svelte` and `astro` with `formatting.prettierd.with({ extra_filetypes = { "astro", "svelte" }})` and it works fine.
I think we should add those in the `filetypes` entry.
> [!note]
> [Eslint lsp](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint) now is updated to work with these filetypes

feat(prettier, prettierd): added `svelte` and `astro` filetypes

---

lua/null-ls/methods.lua

Not sure if the `deepcopy` is needed, in some languages iterating while mutating can give weird results.

fix: remove use of deprecated vim.tbl_add_reverse_lookup

---

lua/null-ls/utils/init.lua
lua/null-ls/utils/tbl_flatten.lua

fix: replace tbl_flatten to flatten():totable() if using nvim-0.10

---

lua/null-ls/builtins/formatting/ktlint.lua

The ktlint formatter clobbers your current Neovim buffer with log errors and warnings. This is especially problematic when working with Kotlin Script files. 
If you have something like this in your buffer:
```
#!/usr/bin/env kotlin
println("Hello World!")
```
and write the file, triggering the formatter, you'll end up with something like this:
```
04:27:56.342 [main] WARN com.pinterest.ktlint.cli.internal.KtlintCommandLine -- Can not parse input from <stdin> as Kotlin, due to error below:
Not a valid Kotlin file (3:1 expecting a top level declaration)
Now, trying to read the input as Kotlin Script.
#!/usr/bin/env kotlin
println("Hello World!")
```
I just went through some old PR's, and it looks like a similar thing happened on the diagnostic side, and they came up with the same fix: …

fix(ktlint): bug where buffer is clobbered by ktlint formatter

---

lua/null-ls/builtins/formatting/opentofu_fmt.lua

Hi! I have been an avid user of null-ls before, and switched to none-ls.nvim. Thanks for keeping this project alive 👍 
This adds the `opentofu-fmt` formatter, in addition to terraform. It is mutually exclusive with the terraform one, as both are use to format the terraform filetypes.
Most of the code is duplicate from the terraform one, but I don't think there is a simpler/more straightforward way to include opentofu in the codebase. If there is, feel free to point me in the right direction. 
Opentofu is a fork which maintains the open source Apache 2.0 license of Terraform, after it switched to the non opensource BSL. See its [manifesto](https://opentofu.org/manifesto/).
Not sure if relevant, but I would be happy to maintain this formatter.

feat: add opentofu-fmt formatter

---

doc/MAIN.md

Hey!
I'm in an ongoing pursuit of adding none-ls to my configuration. While browsing the docs, I stumbled across this difficult sentence.
> Sources can also define a **name**, which allows integrations to see if sources
> null-ls has already registered their sources to prevent duplicate registration.
While the sentence gets the point across after 2 or 3 reads, I feel that it could be made more clearer. Especially as it is among the first sentences readers consume when browsing through the docs, just as I did.
Thanks for the great work! Can't wait to continue to try none-ls!

doc: rephrase source name explanation

---

lua/null-ls/builtins/diagnostics/sqlfluff.lua

Hi, I'm new here! When I tried to setup my neovim environment last week, I found an update of `sqlfluff lint` output when ver 3.0.0 released, leading to unaesthetics diagnostics injection.Hopefully, this PR could help.
- As mentioned in sqlfluff [changelog](https://github.com/sqlfluff/sqlfluff/blob/main/CHANGELOG.md), the serialized output of `sqlfluff lint` renamed from `line_pos` and `line_no` to `start_line_pos` and `start_line_no`.
- Below is the printed `ipairs(params.output)` from neovim `:message`

builtins/diagnostics: update `sqlfluff lint` output format

---

doc/BUILTINS.md
lua/null-ls/builtins/formatting/typstyle.lua

Hello, this adds the [typstyle](https://github.com/Enter-tainer/typstyle/) formatter for `typst` files.
One thing I'm not 100% sure on is if I needed to update the `doc/BUILTINS.md` file or not to reflect this change -- seems there's a CI runner that auto updates the docs. Wasn't sure if that covered generating that or not.
Let me know if you desire any changes, I'll be happy to make 'em.

feat(builtins): add typstyle formatter for typst

---

lua/null-ls/builtins/formatting/erb_lint.lua

An output:match is performed to detect the header of the linter output to exclude it from being injected into the buffer. 
However, it matches on `==`, which is also a legitimate Ruby operator.
When `==` is encountered in the code, it causes the buffer up to and including that operator to be deleted.
Because the linter output uses 16 `=` symbols in its header, adding an additional `==` to the match will still work while not causing false matches with legitimate uses of `==`.

fix(builtins): prevent erb_lint false header match

---

lua/null-ls/builtins/diagnostics/vale.lua

Currently the vale builtin gets the cwd for the spawned process from the root directory, e.g.
```
[DEBUG Mon 15 Jul 11:27:58 2024] 
/Users/ian/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/helpers/generator_factory.lua:329: 
spawning command "vale" 
at /Users/ian/projects/my-project with args { "--no-exit", "--output", "JSON", "--ext", ".md" }
```
When we specify the cwd function for the builtin (as in this PR), we see the process spawning from the directory of the file being processed, e.g. file `foo/bar/my-file.md` (with the change in this PR) we see the debug log
```
[DEBUG Mon 15 Jul 11:28:25 2024]
/Users/ian/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/helpers/generator_factory.lua:329:
spawning command "vale" 
at /Users/ian/projects/my-project/foo/bar with args { "--no-exit", …
```

builtins/vale: allow per directory configuration override

---

lua/null-ls/helpers/generator_factory.lua

to be compatible with cppcheck --file-filter=<path> 
cppcheck by default strips the root path, and it did not seem possible to build that path in any way other than adding this as an option. 
It might be good to be able to allow users to add their own fnamemodify args somehow, but I thought this was a simple and easy fix

fix: add RELPATH to parse_args

---

lua/null-ls/generators.lua

Improvement over https://github.com/nvimtools/none-ls.nvim/pull/173
I noticed that the diagnostics weren't cleared when going from 1 diagnostic result to 0, and that's because after_each is not being called when there are no diagnostics.
This fixes that by calling it in that scenario.

Clear diagnostics when there are no more results

---

lua/null-ls/builtins/completion/luasnip.lua

luasnip returns the description as a table. For example the following luasnippet
```
s({
trig ="test",
name = "Testing Snippet",
dscr = "This descriptions breaks cmp",
},
fmta(
[[
Testing <snippets>
]], {
snippets = i(0),
})),
```
The completion item detail is created as a table
```
{
data = {
filetype = "lua",
ft_indx = 2,
show_condition = <function 1>,
snip_id = 1,
type = "luasnip"
},
detail = { "This descriptions breaks cmp" },
documentation = {
kind = "markdown",
value = "Testing Snippet _ `[lua]`\n---\nThis descriptions breaks cmp\n```lua\nTesting $0\n```"
},
kind = 15,
label = "test",
word = "test"
}
```
This breaks `hrsh7th/nvim-cmp` that expects this value to be a string. With this change completions are created without errors.

Ensure item.detail is a string

---

lua/null-ls/utils/cosmiconfig.lua

Cosmiconfig will check `.{NAME}rc.mjs`, but none-ls ignores them.
https://github.com/cosmiconfig/cosmiconfig

fix: add `.{NAME}rc.mjs` to cosmiconfig file patterns

---

lua/null-ls/builtins/formatting/biome.lua

I tested formatting with both CSS and GraphQL as officially supported here:
https://biomejs.dev/internals/language-support/

builtins/biome: Add CSS and GraphQL as supported filetypes

---

doc/BUILTINS.md
lua/null-ls/builtins/code_actions/textlint.lua

Hi! Thank you for maintaining this project!
This adds a textlint code action. textlint can be used for text editing and, depending on the rules used, may suggest corrections. This change makes it easier to apply those changes using code actions.
I use textlint in Japanese and the replacement process is somewhat complicated because it deals with multibyte characters. At least as far as I have done some experimentation, this works correctly.
Most of the code was created using textlint's diagnostic and proselint code action as a reference. I would be happy to maintain this code action.

feat(builtins): add code action for textlint

---

lua/null-ls/builtins/formatting/cbfmt.lua
lua/null-ls/builtins/formatting/treefmt.lua

`condition` isn't used by `generator_opts`. I believe it used to be, but that was removed in
<https://github.com/nvimtools/none-ls.nvim/commit/ef4eae66de5a90e0ca9cbeac90001064427ce763>.
The fix is simple: just pass this directly to `make_builtin`, [it's a real
option](https://github.com/nvimtools/none-ls.nvim/blob/ae1cffae6d8defb1930028ad5a58f912e14a61e2/lua/null-ls/helpers/make_builtin.lua#L11).

Fix broken conditions

---

doc/BUILTINS.md
lua/null-ls/builtins/diagnostics/erb_lint.lua
lua/null-ls/builtins/formatting/erb_lint.lua

Beginning with version 0.7.0, the new executable command is `erb_lint`.

builtins/erblint: update cmd to erb_lint

---

lua/null-ls/builtins/code_actions/gomodifytags.lua

add some improvements to the builtin gomodifytags code actions:
1. allow the code action to be triggered in more places
2. add option to add tag with -transform flag
before:
after:

builtins/gomodifytags: allow more places and add transform tag

---

doc/BUILTINS.md
lua/null-ls/builtins/formatting/duster.lua

[Duster](https://github.com/tighten/duster) combines different PHP formatters and linters and runs them all simultaneously. It should work similarly to [Pint](https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/builtins/formatting/pint.lua), [PHPCS](https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/builtins/formatting/phpcbf.lua), or [PHP-CS-Fixer](https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/builtins/formatting/phpcsfixer.lua) (since it wraps those packages).

builtins/formatting: add duster

---

doc/BUILTINS.md
doc/builtins.json
lua/null-ls/builtins/_meta/completion.lua
lua/null-ls/builtins/completion/nvim_snippets.lua

https://github.com/garymjr/nvim-snippets

builtins/completion: add nvim-snippets source

---

doc/builtins.json
lua/null-ls/builtins/_meta/filetype_map.lua
lua/null-ls/builtins/_meta/formatting.lua
lua/null-ls/builtins/diagnostics/sqruff.lua
lua/null-ls/builtins/formatting/sqruff.lua

Add support for `sqruff` diagnostics, and formatting.

builtins: add sqruff

---

lua/null-ls/helpers/cache.lua
lua/null-ls/rpc.lua

This completes <https://github.com/nvimtools/none-ls.nvim/issues/198>. The only tricky bit was that our cache helpers can no longer assume their key is present in the cache (as the cache can get reset).
I could have done this with a Lua metatable with a default value instead. Please let me know if you'd prefer that approach!

feature: clear cache when stopping lsp client

---

doc/HELPERS.md
lua/null-ls/helpers/cache.lua
lua/null-ls/helpers/command_resolver.lua
lua/null-ls/helpers/generator_factory.lua
lua/null-ls/helpers/make_builtin.lua
test/spec/client_spec.lua
test/spec/helpers/cache_spec.lua
test/spec/helpers/generator_factory_spec.lua

This implements part of
<https://github.com/nvimtools/none-ls.nvim/issues/193>.
`dynamic_command` is now async, but it does not run immediately when
opening buffers. I plan to implement that in a followup PR.

helpers: make `dynamic_command` async

---

lua/null-ls/helpers/cache.lua

Sorry about this! This got duplicated when rebasing 43b7bb58793b7d2e892656accf393f767c508a70.

Remove duplicate `_reset` function

---

doc/HELPERS.md
lua/null-ls/builtins/_test/dynamic_command_code_action.lua
lua/null-ls/client.lua
lua/null-ls/helpers/cache.lua
lua/null-ls/helpers/command_resolver.lua
lua/null-ls/helpers/generator_factory.lua
test/spec/e2e_spec.lua

This allows generators to pre-compute `dynamic_command` if it's
time consuming to compute.
This completes https://github.com/nvimtools/none-ls.nvim/issues/218
I implemented this in 2 commits, I recommend reading them independently.

helpers: run `dynamic_command` immediately when opening a buffer

---

lua/null-ls/builtins/completion/nvim_snippets.lua

Problem: `require("snippets").get_loaded_snippets()` relies on the state thet can be outdated (both with `create_autocmd = false` and true because of insufficient built-in autocommand).
Solution: use `require("snippets").load_snippets_for_ft(filetype)` directly.

nvim-snippets: don't rely on global snippet list

---

doc/HELPERS.md
lua/null-ls/builtins/formatting/nix_flake_fmt.lua
lua/null-ls/helpers/cache.lua

This implements a builtin formatter that (essentially) invokes `nix fmt` on the given buffer. I called it `"nix flake fmt"`, even though the underlying command is `nix fmt`, because I didn't want people to confuse it with none-ls's pre-existing [`nixfmt` builtin formatter](https://github.com/nvimtools/none-ls.nvim/blob/0e0a940477cc08fa7b1799384a1d668058ed4e61/doc/BUILTINS.md#nixfmt). Naming is hard.
This was pretty tricky to build. Issues I ran into:
- `nix fmt` is slow enough that it's unbearable to run every time you save a buffer. The slowness is the time spent evaluating all the relevant nix code each time, so I opted to cache the result.
- I wanted to cache this per *project* rather than per buffer, so I added a new `by_bufroot` cache helper (inspired by the existing [`by_bufnr` …

builtins/formatting: add "nix flake fmt" builtin formatter

---

lua/null-ls/client.lua
test/spec/client_spec.lua

Neovim is moving towards dropping the old function style (`.`) of invoking these in favor of method style (`:`). We added support for that in
https://github.com/nvimtools/none-ls.nvim/commit/94d024e6550e53c70c3ab765c476a0158b65f564, but it's not perfect: it incorrectly assumes that if you're using nvim-0.11 then *all* invocations of these helpers are method style. I imagine that's true for core-neovim, but there are still plugins in the ecosystem using `.` style. For example, see
<https://github.com/lukas-reineke/lsp-format.nvim/blob/v2.7.1/lua/lsp-format/init.lua#L260>, which I use with Neovim nightly.

client: dynamically detect method style calls

---

lua/null-ls/logger.lua
test/spec/builtins/diagnostics/regal_spec.lua

Since https://github.com/neovim/neovim/pull/31900 it's using `nvim_echo` which cannot be called in fast mode.

fix(logger): schedule vim.notify

---

lua/null-ls/config.lua
lua/null-ls/sources.lua
lua/null-ls/utils/init.lua

`:checkhealth vim.deprecated` complained about it.

utils: use non-deprecated vim.validate form for Nvim 0.11

---

doc/BUILTINS.md
doc/builtins.json
lua/null-ls/builtins/_meta/filetype_map.lua
lua/null-ls/builtins/_meta/formatting.lua
lua/null-ls/builtins/formatting/cljfmt.lua

This adds cljfmt in addition to the existing ones. It is a really popular formatter in the community and it would be great to have it available.

feat(builtins): Add cljfmt formatter for clojure code

---

lua/null-ls/client.lua

Addresses recent breaking change introduced in PR #32503, where the
internal mapping table `_request_name_to_capability` was moved from
`vim.lsp` to `vim.lsp.protocol`.
See [PR #32503](https://github.com/neovim/neovim/pull/32503)
This change ensures compatibility with both older and newer versions
by checking both locations for the mapping table. It uses a fallback
mechanism for locating the mapping, accommodating the API change.
Fixes #252

fix: adapt to LSP capability mapping change

---

lua/null-ls/helpers/diagnostics.lua

Implements fix described in #226
Also in 0.11, `vim.str_byteindex`'s API was changed to clarify utf-X handling, so I added that version as well behind a `has_version` guard.
As stated in the issue, I am convinced that this is correct, since I haven't encountered any problems while running this fix daily for the last 2 months. However, I am not sure if/how to write tests for this behavior.

fix: correctly calculate unicode line length

---

lua/null-ls/builtins/diagnostics/gccdiag.lua
lua/null-ls/helpers/diagnostics.lua

- **feat: apply diagnostics by filename in `multiple_files`**
Added this here since maybe other generators may return diagnostics by filename too in the future

Fix gccdiag diagnostics for multiple files

---

lua/null-ls/builtins/diagnostics/opentofu_validate.lua
lua/null-ls/builtins/formatting/opentofu_fmt.lua

tl;dr: There is already `formatting.opentofu_fmt`, and as proprietary Terraform
and OpenTofu will likely diverge (further) in the future, add its own
diagnostic to be future-proof.

builtins: opentofu: add `validate` diagnostic, fix `fmt` description 

---

doc/BUILTINS.md
lua/null-ls/builtins/diagnostics/golangci_lint.lua
lua/null-ls/helpers/generator_factory.lua

Resolves #256
I've tested this with v1 and v2 by creating a linter issue in:
1. File in Go module at git root with `.golangci.yml`
2. File in Go sub_package_ of Go module
3. File in Go sub_module_ with `.golangci.yml` in the in the git root directory
4. File in Go sub_module_ with no `.golangci.yml` in git repo
To use v1 when v2 is installed globally (or vise versa), one can install the preferred version in `.bin` in the git root directory and configure the linter as so:
```lua
null_ls.builtins.diagnostics.golangci_lint.with({
prefer_local = ".bin",
})
```
I have verified that this works by installing v1 in my path and v2 in `.bin` and a v2 config.
Note that this PR seems to work regardless of the `relative-path-mode` setting the user may configure, since the absolute path of the package …

feat(builtins): Add golangci-lint v2 support

---

lua/null-ls/builtins/diagnostics/golangci_lint.lua

I've been experimenting with latest fix #265. Here are my thoughts on it.
---
Fixed `DIRNAME`.Documentation with motivation: https://golangci-lint.run/welcome/quick-start/
> Directories are NOT analyzed recursively. To analyze them recursively append /... to their path. It's not possible to mix files and packages/directories, and files must come from the same package.
---
Also I rolled back `cwd` function, because `.golangci.yml` is not always the name of the config file but the config usually always in the root of the project (same as `go.mod`).

fix(builtins): fix directory for golangci-lint

---

lua/null-ls/builtins/formatting/csharpier.lua

see: https://github.com/belav/csharpier/blob/main/CHANGELOG.md#rework-the-cli-to-use-commands-and-arguments-1321

fix(csharpier): switched to new formatting command based on recent csharpier 1.0.0 breaking changes 

---

lua/null-ls/builtins/formatting/nix_flake_fmt.lua

This fixes a bug with `nix_flake_fmt` where it doesn't handle flakes with a "formatter" package. I also did some refactoring in separate commits keep things clean. I suggest reading the commits independently.
- **refactor(fix nix_flake_fmt): split `find_nix_fmt` into smaller functions**
- **refactor(nix_flake_fmt): pass data as JSON rather than ad-hoc lines**
- **fix(nix_flake_fmt): handle flakes with a `formatter` package**
IMO, this plugin has too much nix specific knowledge in it. I've submitted https://github.com/NixOS/nix/pull/13063 to core nix to add a `nix fmt --print-command` option. That would allow us to delete a lot of code in this PR.

fix(nix_flake_fmt): handle flakes with a `formatter` package

---

lua/null-ls/client.lua

fixes issue #276
In function `on_init`, tries to get `method_to_required_capability_map` from `lsp.protocol._request_name_to_server_capability` when in neovim nightly.

fix (client.lua): fixes issue #276

---

lua/null-ls/logger.lua
test/spec/logger_spec.lua

The plenary log path changed in this PR: https://github.com/nvim-lua/plenary.nvim/pull/607
Anyone who has updated plenary since Feb 11, 2025 has been sent to the old log file when using `:NullLsLog`.

fix: use stdpath("log") dir to find plenary log

---

lua/null-ls/builtins/formatting/nix_flake_fmt.lua

Core `nix` accepted [my PR to add a new `nix formatter build` command](https://github.com/NixOS/nix/pull/13063)!
That means we can (eventually) get rid of this huge mess of code. I'm excited to try out the new feature, so I (unfortunately) made things even more complicated by adding a "new" and and "old" codepath. I've structured things so somebody with no knowledge of this code could remove the legacy codepath in the future.

chore: rework `nix_flake_fmt` to use the new `nix formatter` subcommand

---

lua/null-ls/builtins/formatting/nix_flake_fmt.lua

`get_flake_ref` can return `nil`, so we need to handle that scenario.

fix: don't assume `flake_ref` exists

---

lua/null-ls/builtins/diagnostics/checkstyle.lua

When the checkstyle source receives a diagnostic back from the checkstyle command, it receives a URI in the format of the following:
```java
{
// ...
"results": [
{
"level": "error",
"locations": [
{
"physicalLocation": {
"artifactLocation": {
"uri": "file:/Users/tahminator/personal/demo/src/main/java/com/example/path/demo/DemoApplication.java"
},
"region": {
"startColumn": 27,
"startLine": 8
}
}
}
],
"message": {
"text": "Parameter args should be final."
},
"ruleId": "final.parameter"
}
]
// ...
}
```
But Neovim's diagnostic doesn't support this `file:/` extension, and as a result, will not show the error in the opened buffer at all.
<p align="center">Should show an error here, but doesn't</p>
If you use a plugin like `trouble.nvim`, you'll be able to see the actual error in the list of …

fix(checkstyle)!: remove the "file:" prefix from the artifact URI

---

doc/CONTRIBUTING.md
lua/null-ls/builtins/diagnostics/cfn_lint.lua

cfn-lint is broken if you pass "-" as a filename for stdin, but understands receiving no filenames (and stdin not being a tty) as meaning it should use stdin as the source.
Tested with cfn-lint 1.38.0.

fix(cfn_lint): Fix cfn-lint arg for stdin

---

doc/BUILTINS.md
doc/CONTRIBUTING.md
doc/builtins.json
lua/null-ls/builtins/_meta/diagnostics.lua
lua/null-ls/builtins/_meta/filetype_map.lua
lua/null-ls/builtins/diagnostics/trivy.lua

- Added new filetypes:
- `helm` - Helm files.
- `dockerfile` - Dockerfiles.
- Adapt diagnostics to parse from 'stderr' (https://github.com/aquasecurity/trivy/pull/2289)
- Update message structure to include trivy misconfiguration ID as diagnostic `code`.

chore: Update Trivy Diagnostics

---

lua/null-ls/builtins/diagnostics/markdownlint_cli2.lua

markdownlint_cli2 prints usage and exits when no targets are specified.
<details>
<summary>debug log</summary>
```
[DEBUG Sat 26 Jul 2025 05:08:29 PM JST] /home/me/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/helpers/generator_factory.lua:359: spawning command "markdownlint-cli2" at /home/me/Documents/notes with args {}
[TRACE Sat 26 Jul 2025 05:08:29 PM JST] /home/me/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/helpers/generator_factory.lua:240: error output: markdownlint-cli2 v0.18.1 (markdownlint v0.38.0)
https://github.com/DavidAnson/markdownlint-cli2
Syntax: markdownlint-cli2 glob0 [glob1] [...] [globN] [--config file] [--fix] [--help]
Glob expressions (from the globby library):
- * matches any number of characters, but not /
- ? matches a single character, but not /
- ** …
```

fix(diagnostics): fix markdownlint-cli2 failing

---

lua/null-ls/builtins/formatting/bean_format.lua

`bean-format` from beancount v3 requires '-' argument to read from stdin.
beancount v2 works both ways.
```
$ bean-format --version
Beancount 3.1.0
$ bean-format <ledger.beancount
Usage: bean-format [OPTIONS] FILENAME
Try 'bean-format --help' for help.
Error: Missing argument 'FILENAME'.
```
With '-' both version works:
```
$ bean-format --version
Beancount 2.3.6
$ bean-format - <ledger.beancount
;; -*- mode: org; mode: beancount; -*-
...
$ bean-format --version
Beancount 3.1.0
$ bean-format - <ledger.beancount
;; -*- mode: org; mode: beancount; -*-
...
```

fix(bean_format): fix bean_format for beancount v3

---

lua/null-ls/builtins/formatting/forge_fmt.lua

If a foundry/forge project is not in the $ROOT path (e.g. /repo/contracts-project), the `forge` command runs without loading the configuration from the `foundry.toml` file, unless a `--root PATH` is passed as argument. 
This happens even if you open the `/repo/contracts-project` folder directly, because `$ROOT` is still set to `/repo` if `/repo/.git` exists.
This PR adds a dynamic cached `cwd` for the `forge_fmt` formatter so that each buffer runs from the foundry project root.

fix(forge_fmt): cwd to the first parent with the foundry.toml file
